Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -114,6 +114,8 @@ runs:
         if [ -n "${{ inputs.testResultPath }}" ]; then
           if [ !-f "${{ inputs.testResultPath }}" ]; then
             echo "Error: Invalid test result path" ; exit 1;
+          else
+            echo "Error: Invalid test result path" ; exit 1;
           fi
           [[ "${{ inputs.testResultPath }}" = *[!\ ]*  ]] || { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
