Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -97,6 +97,7 @@ runs:
     - name: Run Eggplant DAI Test Configuration
       run: |
         [[ "${{ inputs.serverURL }}" ]] || { echo "Error: Missing server URL" ; exit 1; }
+        [[ "${{ inputs.testResultPath }}" ]] || { echo "Error: Missing testResultPath" ; exit 1; }
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
         COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }} --client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --log-level=${{ inputs.logLevel }}"
         
@@ -105,13 +106,7 @@ runs:
         fi
        
         if [ -n "${{ inputs.testResultPath }}" ]; then
-          echo "line 108";
-          [[ "${{ inputs.testResultPath }}" ]] || { echo "Error: Missing testResultPath" ; exit 1; }
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
-        fi
-        
-        if [[ "${{ inputs.testResultPath }}" == *[!\ ]*  ]]; then
-        { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
         fi
         
         if [ ${{ inputs.dryRun }} == true ]; then
