Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -109,8 +109,8 @@ runs:
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
         
-        if [[ "${{ inputs.testResultPath }}"=="" ]]; then
-        { echo "Error: Missing test result path" ; exit 1; }
+        if [[ has_field(yml(), "testResultPath")]]; then
+        { echo "Error: have test result path" ; exit 1; }
         fi
         if [[ "${{ inputs.testResultPath }}" == *[!\ ]*  ]]; then
         { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
