Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -97,19 +97,15 @@ runs:
     - name: Run Eggplant DAI Test Configuration
       run: |
         [[ "${{ inputs.serverURL }}" ]] || { echo "Error: Missing server URL" ; exit 1; }
+        [[ "${{ inputs.testResultPath }}" ]] || { echo "Error: Missing test result path" ; exit 1; }
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
         COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }} --client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --log-level=${{ inputs.logLevel }}"
         
         if [ -n "${{ inputs.CACertPath }}" ]; then
           COMMANDSTR+=" --ca-cert-path=${{ inputs.CACertPath }}"
         fi
-        
-        if [[ "${{ inputs.testResultPath }}" ]]; then 
-          { echo "Error: Missing test result path" ; exit 1; }
-        fi
-          
+       
         if [ -n "${{ inputs.testResultPath }}" ]; then
-          
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
         
