Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -104,11 +104,10 @@ runs:
           COMMANDSTR+=" --ca-cert-path=${{ inputs.CACertPath }}"
         fi
        
-        if [ -z "${{ inputs.testResultPath }}" ]; then
-           { echo "Error: Missing testResultPath" ; exit 1; }
-        fi
-        
         if [ -n "${{ inputs.testResultPath }}" ]; then
+          if [ -z "${{ inputs.testResultPath }}" ]; then
+           { echo "Error: Missing testResultPath" ; exit 1; }
+          fi
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
         
