Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -104,8 +104,11 @@ runs:
           COMMANDSTR+=" --ca-cert-path=${{ inputs.CACertPath }}"
         fi
         
+        if [[ "${{ inputs.testResultPath }}" ]]; then 
+          { echo "Error: Missing test result path" ; exit 1; }
+          
         if [ -n "${{ inputs.testResultPath }}" ]; then
-          [[ "${{ inputs.testResultPath }}" ]] || { echo "Error: Missing test result path" ; exit 1; }
+          
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
         
