Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -105,7 +105,7 @@ runs:
         fi
        
         if [ -z "${{ inputs.testResultPath }}" ]; then
-          echo "Error : missing test result path";
+          echo "Error : missing test result path"; exit 1;
         else
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi 
