Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -103,20 +103,22 @@ runs:
         
         if [ -n "${{ inputs.CACertPath }}" ] then
           if [ ! -e "${{ inputs.CACertPath }}" ] then
-            {echo "Error: Invalid CA Cert Path" ; exit 1;}
+            echo "Error: Invalid CA Cert Path" ; 
+            exit 1;
           fi
           COMMANDSTR+=" --ca-cert-path=${{ inputs.CACertPath }}"
         fi
         
         if [ -n "${{ inputs.testResultPath }}" ] then
           if [ ! -d "${{ inputs.testResultPath }}" ] then
-            echo "Error: Invalid test result path" ; exit 1;
+            echo "Error: Invalid test result path" ; 
+            exit 1;
           fi
           [[ "${{ inputs.testResultPath }}" = *[!\ ]*  ]] || { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
         
-        if [ ${{ inputs.dryRun }} == true ]; then
+        if [ ${{ inputs.dryRun }} == true ] then
           COMMANDSTR+=" --dry-run"
         fi
         
