Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -98,13 +98,20 @@ runs:
       run: |
         [[ "${{ inputs.serverURL }}" ]] || { echo "Error: Missing server URL" ; exit 1; }
         [[ "${{ inputs.serverURL }}" = *[!\ ]*  ]] || { echo "Error: Server URL consists of empty spaces only." ; exit 1; }
+        
         COMMANDSTR="${{ inputs.serverURL }} ${{ inputs.testConfigID }} --client-id=${{ inputs.clientID }} --request-timeout=${{ inputs.requestTimeout }} --request-retries=${{ inputs.requestRetries }} --backoff-factor=${{ inputs.backoffFactor }} --poll-interval=${{ inputs.pollInterval }} --log-level=${{ inputs.logLevel }}"
         
-        if [ -n "${{ inputs.CACertPath }}" ]; then
+        if [ -n "${{ inputs.CACertPath }}" ] then
+          if [ ! -e "${{ inputs.CACertPath }}" ] then
+            {echo "Error: Invalid CA Cert Path" ; exit 1;}
+          fi
           COMMANDSTR+=" --ca-cert-path=${{ inputs.CACertPath }}"
         fi
         
-        if [ -n "${{ inputs.testResultPath }}" ]; then
+        if [ -n "${{ inputs.testResultPath }}" ] then
+          if [ ! -d "${{ inputs.testResultPath }}" ] then
+            echo "Error: Invalid test result path" ; exit 1;
+          fi
           [[ "${{ inputs.testResultPath }}" = *[!\ ]*  ]] || { echo "Error: Test result path consists of empty spaces only." ; exit 1; }
           COMMANDSTR+=" --test-result-path=${{ inputs.testResultPath }}"
         fi
